### ISSUE TITLE
Create an API Filter the shelter by sheltername, address, zipcode, city or state

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#11]
Create an API Filter the shelter by address, zipcode, city or state

**Comment by suryayadavalli** [comment]
ETA: 12/14

**Comment by suryayadavalli** [comment]
Commit id: https://github.com/servinglynk/hslynk-open-source/commit/499d565db149a3eef9d012cda93c92e4569976a6

**Comment by suryayadavalli** [comment]
Commit id: https://github.com/servinglynk/hslynk-open-source/commit/ece3b5ab62063e802354cd27e130d99f769041cc

documentation link: https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/shelters/GET_all_shelter

**Comment by logicsandeep** [comment]
Thanks @suryayadavalli , Will check.

**Comment by logicsandeep** [comment]
This issue can be closed.
