### ISSUE TITLE
Include client name also in the response for GET ​bedunit's reservation API

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#13]
The GET ​The GET ​/shelters​/{shelterid}​/areas​/{areaid}​/rooms​/{roomid}​/bedunits/{bedunitid}/occupants and /shelters​/{shelterid}​/areas​/{areaid}​/rooms​/{roomid}​/bedunits/{bedunitid}/reservation API needs to fetch clientId and clientName API needs to fetch clientId and clientName.
When showing the occupants in a room we have to call /occupants API to get the client ID and then we have to get clients/{clientid} API to show the client name. It would be great to have the client ID and name sent as part of the bedunits API.

**Comment by suryayadavalli** [comment]
ETA : 12/18

**Comment by suryayadavalli** [comment]
Commit id : https://github.com/servinglynk/hslynk-open-source/commit/c78b161ba74d0abe15702a62059111fe12430edb
documentation link: https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API

**Comment by logicsandeep** [comment]
This is working as expected.
