### ISSUE TITLE
The GET /bedunits API returns the same response for all the rooms

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#14]
https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/bedunits/get_shelters__shelterid__areas__areaid__rooms__roomid__bedunits

**Comment by suryayadavalli** [comment]
@logicsandeep :  I am not able to understand the issue with the title you set up. Please include the response and elaborate on this issue with further details. You can assign the ticket back to me after furnishing the details.

**Comment by logicsandeep** [comment]
This issue is fixed now. I think this was fixed as part of your previous release.
