### ISSUE TITLE
The /occupants and /reservation API returns a 404

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#15]
https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/bedunit-occupants/get_shelters__shelterid__areas__areaid__rooms__roomid__bedunits__bedunitid__occupants

https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/bedunit-reservations/get_shelters__shelterid__areas__areaid__rooms__roomid__bedunits__bedunitid__reservations
<img width="1417" alt="Screen Shot 2020-12-11 at 8 35 45 AM" src="https://user-images.githubusercontent.com/4108057/101909729-e7c6f200-3b8b-11eb-86c9-41fb2b412258.png">

**Comment by suryayadavalli** [comment]
Closed

**Comment by suryayadavalli** [comment]
Reservations documentation link : https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/bedunit-reservations/post_bedunits__bedunitid__reservations


Occupants documentation link:  https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/bedunit-occupants/post_bedunits__bedunitid__occupants

**Comment by logicsandeep** [comment]
@suryayadavalli , I clearly provided you an example about the reservations API returning 404. Please let me know if you need more information.

**Comment by suryayadavalli** [comment]
@logicsandeep : No need for additional information. Please check the APIs now.  The documentation is corrected and I provided the links the documentation in this ticket, above.

**Comment by logicsandeep** [comment]
The /occupants and /reservations APIs are returning a 404, Please also test all (POST, PUT, GET, DELETE) the APIs related to /occupants and /reservations.

https://api.hslynk.com/bed-inventory-api/rest/shelters/94599d8c-e0c3-4f67-9611-d2de9f40074c/areas/9eff41b9-68e6-4802-8825-6bda8128ed05/rooms/5a632c51-bc28-4746-acde-0a068332714f/bedunits/a0ba3a2d-57be-439d-8f7c-8f1ed1739ca9/reservations
https://api.hslynk.com/bed-inventory-api/rest/shelters/94599d8c-e0c3-4f67-9611-d2de9f40074c/areas/9eff41b9-68e6-4802-8825-6bda8128ed05/rooms/5a632c51-bc28-4746-acde-0a068332714f/bedunits/a0ba3a2d-57be-439d-8f7c-8f1ed1739ca9/occupants

<img width="943" alt="Screen Shot 2020-12-15 at 4 04 41 PM" src="https://user-images.githubusercontent.com/4108057/102272812-5939d400-3eef-11eb-8eaa-fcc2c377af51.png">
<img width="871" alt="Screen Shot 2020-12-15 at 4 04 55 PM" src="https://user-images.githubusercontent.com/4108057/102272817-5ccd5b00-3eef-11eb-80d8-76513dd834a6.png">

**Comment by suryabi** [comment]
@logicsandeep : screen shot probably doesnt help replaying the same request. Please furning the API call, request body and response

**Comment by logicsandeep** [comment]
@suryabi  Please check my comment above.  It has the full URL and the screen shot has the response code. Please let me know if you need further information.

**Comment by suryayadavalli** [comment]
@logicsandeep : I updated the ticket earlier with updated API documentation links. From the comments you have above looks like you still have shelter Id, area Id, room Id in the path parameters which are not used any more. Please double check. 

![image](https://user-images.githubusercontent.com/10738348/102282600-b29d0580-3ee5-11eb-8ba2-8b508b9013c0.png)

![image](https://user-images.githubusercontent.com/10738348/102282685-cfd1d400-3ee5-11eb-9834-23ec65a10221.png)

**Comment by logicsandeep** [comment]
Aha. Thanks @suryabi , It was not clear from your earlier response that the API signature is changed in the API documentation. This is clear now. Also, my browser cache pointed me to the API documentation with out your updates.
![Uploading Screen Shot 2020-12-15 at 7.06.56 PM.png…]()

**Comment by logicsandeep** [comment]
I'll close this issue after testing.

**Comment by logicsandeep** [comment]
@suryabi , How about the room reservation APIs ? I don't see a change in the path. Can you please confirm if these will work ?
<img width="1395" alt="Screen Shot 2020-12-15 at 7 16 15 PM" src="https://user-images.githubusercontent.com/4108057/102288260-251fdc80-3f0a-11eb-86d9-487ffff7eba6.png">

**Comment by suryayadavalli** [comment]
@logicsandeep Yes. APIs should work as per the spec
