### ISSUE TITLE
404 when calling GET shelters/{shelterid} and shelters/{shelterid}/areas API

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#16]
I'm getting a 404 when calling GET shelters/{shelterid} and shelters/{shelterid}/areas API
<img width="764" alt="Screen Shot 2020-12-11 at 2 01 38 PM" src="https://user-images.githubusercontent.com/4108057/101943629-6f772580-3bb9-11eb-8015-cf13ca0c6121.png">

**Comment by suryayadavalli** [comment]
@logicsandeep Both APIs are deployed in production. Those are working fine. 

![image](https://user-images.githubusercontent.com/10738348/101977972-79f7f480-3c77-11eb-9ac9-65ab223c1fde.png)

![image](https://user-images.githubusercontent.com/10738348/101977961-664c8e00-3c77-11eb-82f3-a6f7fe2352ac.png)

Please verify once again.

**Comment by logicsandeep** [comment]
This issue fixed too
