### ISSUE TITLE
GET  rooms/{roomid}/bedunits returns same records for all the rooms

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#18]
GET  rooms/{roomid}/bedunits returns same records for all the rooms

**Comment by suryayadavalli** [comment]
Resolved. 
Commit id: https://github.com/servinglynk/hslynk-open-source/commit/fd7cb2f87ca6553b035a4fb6155d7b4f1dd5ab18

**Comment by logicsandeep** [comment]
This is fixed.
