### ISSUE TITLE
The /shelters API returns the same records irrespective of the startIndex

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#19]
/bed-inventory-api/rest/shelters?startIndex=21&maxItems=20 returns the same records as /bed-inventory-api/rest/shelters?startIndex=0&maxItems=20. Ideally, when the API is called with startIndex=21 It should call records for Page # 2.

**Comment by suryayadavalli** [comment]
Documentation link:  https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/shelters/GET_all_shelter

**Comment by suryayadavalli** [comment]
@logicsandeep : I updated the documentation with pagination parameters that need to be used which were missing earlier. Please check.

**Comment by logicsandeep** [comment]
@suryayadavalli  The shelter APIs have different pagination params when compared to other hmis APIs.

**Comment by suryayadavalli** [comment]
Yes, correct. The new micro service that we have been coming up with uses out of the box pagination mechanism that spring boot offers.

**Comment by eric-jahn** [comment]
@logicsandeep Can we close this?

**Comment by logicsandeep** [comment]
Yes @eric-jahn .  This issue can be closed. I'm not super happy about the fact that the pagination params in this microservice are different than other microservices. But the documentation has the details. so closing the ticket.
