### ISSUE TITLE
API page fixes

### ISSUE THREAD

**Issue by eric-jahn** [hmis-api/bed-and-housing-management#2]
1) [Surya] Title needs to be changed from "Bed Management API" to "Bed and Housing Management API"
1) [Sandeep] The API Source link, "Contact Us", and License links need to be added, as the appear on the other API pages.

**Comment by logicsandeep** [comment]
Added Api Source link. and contact us and license links. I see that @suryayadavalli  changed the title.

**Comment by logicsandeep** [comment]
https://github.com/hmis-api/bed-and-housing-management/commit/d60241da02ee1c8388b049de83b2a5b43510eaa0
