### ISSUE TITLE
The GET /reservations and /occupants API should have a date filter and should return reservations and occupants by a date range.

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#20]
Having a /reservations and /occuptants API with a date range filter will help the apps show reservations and occupants by a date range rather than getting all the reservations for the bed unit.

**Comment by suryayadavalli** [comment]
commit id : https://github.com/servinglynk/hslynk-open-source/commit/a3867a19176fca66ffbcc548d38a5cd0a571dd32 

**Documentation links** :
Bed Unit reservations : https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/bedunit-reservations/get_bedunits__bedunitid__reservations

Bed Unit Occupants :  https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/bedunit-occupants/get_bedunits__bedunitid__occupants

Room reservations: https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/room-reservations/get_shelters__shelterid__areas__areaid__rooms__roomid__reservations

**Comment by logicsandeep** [comment]
This is working as expected.
