### ISSUE TITLE
Additional APIs for bed list management 

### ISSUE THREAD

**Issue by suryayadavalli** [hmis-api/bed-and-housing-management#22]
- GET bed unit reservations for a specific client (for a specific time range)
- GET bed unit occupations for a specific client (for a specific time range)
- GET room reservations for a specific client (for a specific time range)
- GET housing unit reservations for a specific client (for a specific time range)
- GET housing unit occupations for a specific client (for a specific time range)

**Comment by suryayadavalli** [comment]
Commit id:  https://github.com/servinglynk/hslynk-open-source/commit/4ea3ec132943e3611ea8cf923431f2120562d4cb
Documentation link:  https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/clients

**Comment by logicsandeep** [comment]
This can be closed
