### ISSUE TITLE
Room Reservation POST/GET API doesn't work, return 404

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#23]
The following API returns a 404.

https://api.hslynk.com/bed-inventory-api/rest/shelters/94599d8c-e0c3-4f67-9611-d2de9f40074c/areas/9eff41b9-68e6-4802-8825-6bda8128ed05/rooms/5a632c51-bc28-4746-acde-0a068332714f/reservations

**Comment by suryayadavalli** [comment]
@logicsandeep : Please double check. I just verified and no check ins done today. It's working for me. Assigning the issue back to you. Please review and close.

![image](https://user-images.githubusercontent.com/10738348/102974892-42b1ff00-4525-11eb-97bd-484b63df9476.png)

**Comment by logicsandeep** [comment]
This is looked good. I think I was thrown by the typo in the reservedClientId field. Closing this ticket.
