### ISSUE TITLE
Room Occupants POST/GET API is missing in Swagger

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#24]
We don't have APIs to POST/GET related to the /rooms in the API documentation. Are the APIs missing ?

**Comment by suryayadavalli** [comment]
started working on this. ETA 12/30

**Comment by suryayadavalli** [comment]
Resolved.
Commit id: https://github.com/servinglynk/hslynk-open-source/commit/b56db79d9b0b736f2a019fcbf5e9a69ff30d9b1a

Document link :  https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/room-occupants

**Comment by logicsandeep** [comment]
This is working now.
