### ISSUE TITLE
HousingUnit GET API doesn't return any information except Ids

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#25]
The following API returns just IDs and It should return all the elements like name, projectId etc based on the API documentation.

**API**
https://api.hslynk.com/bed-inventory-api/rest/housingunits?page=0&size=20

**Response:**
{"summary":null,"pagination":{"from":0,"returned":20,"total":25,"maximum":30,"sort":null},"housingUnits":[{"id":"dbe08c69-606a-447f-b73e-c308f0c5439a"},{"id":"71daf75d-b2f8-4724-b573-f8e4470a33ae"},{"id":"737d045c-e15e-4a90-b737-84ef13faf9d4"},{"id":"09e32bbf-f47a-4b1c-9965-fb93cab01098"},{"id":"3f35846e-cc3f-4274-9d08-905eeb66fed8"},{"id":"83dbe1e6-3511-405e-8001-f48996b9ab18"},{"id":"b081affc-b3c7-4218-8e40-099a2aff224d"},{"id":"82a716b2-728e-4853-8223-dcfeb34a982f"},{"id":"30db294a-59fb-4cb0-a2a4-4a5c81f19f41"},{"id":"d891ef59-8eb5-4172-af7e-8b66f588ec82"},{"id":"02ae8ea2-c67b-4fc2-ac1c-0281178848eb"},{"id":"88c40e26-8269-43cd-a7d2-0d0c857b5bc4"},{"id":"034c3338-82e3-437a-85fd-0b5909b0d5b9"},{"id":"7b0c96d1-e4e0-4eab-9c22-56477cfd0518"},{"id":"eabc0c45-2719-4c0b-b392-9144f0b38dd5"},{"id":"219f4584-b9cb-49b4-8cb0-e2b43e5cd51e"},{"id":"a71f708d-e26e-495e-bf3f-de37a7e5f3b2"},{"id":"2bd5727b-fa33-4841-822a-fd51f8a709e3"},{"id":"be26b082-af76-45e0-a8dc-cf6e7e703b58"},{"id":"5050a57e-bcf0-4bac-b8cb-096301ae4c30"}]}

**Comment by suryayadavalli** [comment]
You are using test data that is created during my development, which doesn't have any data. Please create your own test data and verify. 

Once you create housing units with valid data, you should see the responses as below.  I have cleaned up dunmy data for you from DB. 

![image](https://user-images.githubusercontent.com/10738348/102968959-d205e500-451a-11eb-8191-a7a9261d3be1.png)



Assigning the issue back to you. Please close after review.

**Comment by logicsandeep** [comment]
This can be closed.
