### ISSUE TITLE
HousingUnit single item GET API doesn't work return 404 not found

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#26]
The following API returns a 404

**API**

https://api.hslynk.com/bed-inventory-api/rest/housingunits/dbe08c69-606a-447f-b73e-c308f0c5439aa

**Response:**

"{
  ""error"" : [ {
    ""code"" : ""ERR_CODE_NOT_FOUND"",
    ""message"" : ""HousingUnit dbe08c69-606a-447f-b73e-c308f0c5439a not found""
  } ]
}"

**Comment by suryayadavalli** [comment]
@logicsandeep : The UUID that you have in the request is not valid. It has a additonal character 'a' at the end. Please double check.

![image](https://user-images.githubusercontent.com/10738348/102968523-062cd600-451a-11eb-8495-fe1c34fa766d.png)


With the proper UUID (corrected the same one) here is the response. Assigning the ticket back to you. Please close.

![image](https://user-images.githubusercontent.com/10738348/102968554-12189800-451a-11eb-9f6a-06e47bfac720.png)

**Comment by logicsandeep** [comment]
Yes, It is working as expected.
