### ISSUE TITLE
HousingUnit Reservation POST API returns unexpected error occurred

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#27]
**API**
http://api.hslynk.com/bed-inventory-api/rest/housingunits/dbe08c69-606a-447f-b73e-c308f0c5439a/reservations

**Response:**
"{
    ""error"": [
        {
            ""code"": ""UNKNOWN"",
            ""message"": ""unexpected error occurred""
        }
    ]
}"

**Comment by suryayadavalli** [comment]
@logicsandeep: Can you please provide request body json

**Comment by suryayadavalli** [comment]
@logicsandeep : assigning the ticket back to you. Please include exact request body.

**Comment by logicsandeep** [comment]
{
	"startDate":1606847460000,
	"endDate":1607020260000,
	"reservedClientId":"76f57a18-abd4-4848-925e-fe88feea1b00"
}

**Comment by logicsandeep** [comment]
Provided you the request body

**Comment by logicsandeep** [comment]
It was a test data issue. I was able to reserver a housing unit from the new data.
