### ISSUE TITLE
HousingUnit Occupants GET API returns 500 internal server

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#28]
HousingUnit Occupants GET API returns 500 internal server.

**API**
http://api.hslynk.com/bed-inventory-api/rest/housingunits/dbe08c69-606a-447f-b73e-c308f0c5439a/occupants

**Response:**
"{
    ""error"": [
        {
            ""code"": ""UNKNOWN"",
            ""message"": ""unexpected error occurred""
        }
    ]
}"

**Comment by suryayadavalli** [comment]
@logicsandeep : when did you see this error. If this is from past please check now.

No check ins done today from my end but when I try the same call I have a proper response. Assigning back to you.

![image](https://user-images.githubusercontent.com/10738348/102967900-ed6ff080-4518-11eb-8f8d-8ea09d6f5904.png)

**Comment by logicsandeep** [comment]
Thanks @suryayadavalli , This is working for me.
