### ISSUE TITLE
Typo in the GET /reservations API.

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#29]
The GET /reservations API returns with a typo. Screen shot below.

<img width="535" alt="Screen Shot 2020-12-22 at 3 58 29 PM" src="https://user-images.githubusercontent.com/4108057/102932615-9b729080-446e-11eb-8c54-aa0aaafe811e.png">

**Comment by suryayadavalli** [comment]
Will fix this typo today.

**Comment by suryayadavalli** [comment]
Resolved.
Commit id: https://github.com/servinglynk/hslynk-open-source/commit/4ea3ec132943e3611ea8cf923431f2120562d4cb

**Comment by logicsandeep** [comment]
This is fixed.
