### ISSUE TITLE
Check-in & Check-out APIs for bed unit occupancy

### ISSUE THREAD

**Issue by suryayadavalli** [hmis-api/bed-and-housing-management#30]

**Comment by suryayadavalli** [comment]
Commit id: https://github.com/servinglynk/hslynk-open-source/commit/f9e3357f4bf9d3056877f0bb1e338df589210356

Check-in documentation link:  https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/bedunit-occupants/post_bedunits__bedunitid__checkin

Check-out document link: https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/bedunit-occupants/put_bedunits__bedunitid__checkout

**Comment by logicsandeep** [comment]
Can you please return the bed's occupancy status in the API response?

https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/bedunit-occupants/post_bedunits__bedunitid__checkin

 https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/bedunit-occupants/put_bedunits__bedunitid__checkout

With out the occupancy status, we will not be able to identify whether the bed is vacant or occupied.

**Comment by logicsandeep** [comment]
The checkin and checkout API does not change bed occupancy.

For Example:
 https://api.hslynk.com/bed-inventory-api/rest/bedunits/d1264714-3527-4b35-8e7f-fd2131161804/checkin
**Request Body:**
  {"clientId":"64b1abe4-dd4f-4305-9d4c-36846e9d9d2c","startDate":1609843966000,"endDate":1611273599000}
**Response:** 
{"id":"1d6ac981-22b3-492b-8575-42081fe080f5","clientId":"64b1abe4-dd4f-4305-9d4c-36846e9d9d2c","startDate":1609843966000,"endDate":1611273599000,"bedUnit":{"id":"d1264714-3527-4b35-8e7f-fd2131161804"}}

Now I'm making an API call to get the bed details.
Bed Unit API.
https://api.hslynk.com/bed-inventory-api/rest/shelters/fa185123-3f58-4cf3-bfe2-d98257512374/areas/feaad10b-7768-4483-aa27-313a3f5980ec/rooms/cbd0ea6d-6c9d-40b7-82a5-fb67a28acb99/bedunits/d1264714-3527-4b35-8e7f-fd2131161804

And as you can see the occupancy = false and it should be true for bedId= d1264714-3527-4b35-8e7f-fd2131161804
**Response:**
{"id":"d1264714-3527-4b35-8e7f-fd2131161804","**occupancy":false**,"occupantCapacity":2,"overflow":false,"room":{"id":"cbd0ea6d-6c9d-40b7-82a5-fb67a28acb99","name":"demo room","occupantCapacity":2,"area":{"id":"feaad10b-7768-4483-aa27-313a3f5980ec","name":"Demo2","description":"d","occupantCapacity":2,"shelter":{"id":"fa185123-3f58-4cf3-bfe2-d98257512374","name":"Demo","address":"","url":"http://loc.com","projectId":"6f9dafea-f0d3-4f31-986c-fc489d24a343","projectType":"1","description":"Demo","occupantCapacity":1}},"shelter":{"id":"fa185123-3f58-4cf3-bfe2-d98257512374","name":"Demo","address":"","url":"http://loc.com","projectId":"6f9dafea-f0d3-4f31-986c-fc489d24a343","projectType":"1","description":"Demo","occupantCapacity":1}}}

**Comment by eric-jahn** [comment]
@suryayadavalli: can @logicsandeep squash the remaining occupancy (and other bed issues)  issue in the comments?

**Comment by suryayadavalli** [comment]
Resolved. 

commit id:  https://github.com/servinglynk/hslynk-open-source/commit/b56db79d9b0b736f2a019fcbf5e9a69ff30d9b1a

**Comment by logicsandeep** [comment]
CheckIn and checkout updates bed occupancy.
