### ISSUE TITLE
BED name (meaningful identifier) 

### ISSUE THREAD

**Issue by suryayadavalli** [hmis-api/bed-and-housing-management#31]
Add name for the. GET, POST. PUT /bedunit/ APIs.
Also make sure to return the bed name for reservations and occupants APIs

**Comment by suryayadavalli** [comment]
Resolved.

Commit id: https://github.com/servinglynk/hslynk-open-source/commit/b56db79d9b0b736f2a019fcbf5e9a69ff30d9b1a

Documentation link:  https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/bedunits/post_shelters__shelterid__areas__areaid__rooms__roomid__bedunits

**Comment by logicsandeep** [comment]
This is working as expected.
