### ISSUE TITLE
Include latitude, longitude,city, state, zipcode and address 1 and address 2 in housingunit POST,PUT and GET Apis

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#32]
Include latitude, longitude,city, state, zipcode and address 1 and address 2 in housingunit POST and GET Apis

**Comment by suryayadavalli** [comment]
Resolved.

Document link: https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/housing%20units

Commit id: https://github.com/servinglynk/hslynk-open-source/commit/b56db79d9b0b736f2a019fcbf5e9a69ff30d9b1a

**Comment by logicsandeep** [comment]
Working as expected.
