### ISSUE TITLE
The GET housingunit API does not have a filter

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#33]
The GET housingunit API does not have a filter like /shelters API
https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/housing%20units/get_housingunits

**Comment by suryayadavalli** [comment]
Resolved.

Document link: https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/housing%20units

Commit id: https://github.com/servinglynk/hslynk-open-source/commit/b56db79d9b0b736f2a019fcbf5e9a69ff30d9b1a

**Comment by logicsandeep** [comment]
Housingunit filter does not work.
GET https://api.hslynk.com/bed-inventory-api/rest/housingunits?q=1245
returns 500 Error code.

**Comment by suryayadavalli** [comment]
Resolved.
Commit id: https://github.com/servinglynk/hslynk-open-source/commit/4a52e4c90e30f9fcd1b5f2f2f77180b2abee516a

**Comment by logicsandeep** [comment]
Filter works fine.
