### ISSUE TITLE
All the APIs related to getting the client shelter/housing unit information should return appropriate identifiers.

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#34]
<img width="1397" alt="Screen Shot 2020-12-30 at 7 49 37 AM" src="https://user-images.githubusercontent.com/4108057/103352568-87cdb800-4a74-11eb-9992-7fb40385c0b5.png">

All the APIs above should have shelterid,areaid, roomId, bedId, and housingunitId (if applicable)
Please look into the response in swagger below, shelterid,areaid, roomId, bedId are missing in the response.

<img width="1255" alt="Screen Shot 2020-12-30 at 7 57 50 AM" src="https://user-images.githubusercontent.com/4108057/103352642-bcda0a80-4a74-11eb-9225-11fcde6431bc.png">

**Comment by suryayadavalli** [comment]
This is resolved.

Commid id:  https://github.com/servinglynk/hslynk-open-source/commit/b56db79d9b0b736f2a019fcbf5e9a69ff30d9b1a

Documentation links: 
https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/clients/get_clients__clientid__bedunits_reservations

https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/clients/get_clients__clientid__rooms_reservations

https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/clients/get_clients__clientid__housingunits_reservations

https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/clients/get_clients__clientid__bedunits_occupants

https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/clients/get_clients__clientid__housingunits_occupants
