### ISSUE TITLE
PUT Bed reservation API returns a 404

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#35]
URL:
https://api.hslynk.com/bed-inventory-api/rest/bedunits/411eb9eb-1d6c-40d4-ac32-c696c993a71b/reservations/609bd3c1-aa7e-4f05-bd69-9c1eeae18b90

Request Body:
{"reservedCleintId":"5bc0b52a-35fa-45b1-8d9d-b0fb1e474fde","startDate":1609804800000,"endDate":1613001599000}

Response:
{
  "error" : [ {
    "code" : "ERR_CODE_NOT_FOUND",
    "message" : " Invalid Client Identification null"
  } ]
}

Please also note that there's typo in the reservedCleintId in the code.

**Comment by eric-jahn** [comment]
@logicsandeep will squash this bug

**Comment by suryayadavalli** [comment]
This is resolved.

Commid id:  https://github.com/servinglynk/hslynk-open-source/commit/b56db79d9b0b736f2a019fcbf5e9a69ff30d9b1a

**Comment by logicsandeep** [comment]
The PUT bed reservation removes the reservedClientId from the response.

Request:
PUT https://api.hslynk.com/bed-inventory-api/rest/bedunits/3db7b281-fc82-4850-919b-2c4fa7013ca7/reservations/11eb4d8a-6959-4f94-8a22-1bdc9a3a127a

Body:
{"reservedClientId":"2ebfc1cc-a1bc-42b6-b86d-92167e5f9bbd","startDate":1610236800000,"endDate":1611705599000}

**GET Bed Reservation:**
https://api.hslynk.com/bed-inventory-api/rest/bedunits/3db7b281-fc82-4850-919b-2c4fa7013ca7/reservations?fromdate=1609045200000&todate=1612673999000

The reservedClientId is not getting populated for "11eb4d8a-6959-4f94-8a22-1bdc9a3a127a"
**Response:**
{
	"pagination": {
		"from": 0,
		"returned": 2,
		"total": 2,
		"maximum": 30,
		"sort": null
	},
	"bedUnitReservations": [{
		"id": "67430811-6cf5-45cf-ad3a-6c8ebbc485ed",
		"reservedClientId": "199b2f2f-44ee-4f85-973c-531819fb6b64",
		"startDate": 1612656000000,
		"endDate": 1614470399000,
		"client": {
			"clientId": "199b2f2f-44ee-4f85-973c-531819fb6b64",
			"dedupClientId": "bc14fad0-91ae-11ea-b546-02fe61f7863e",
			"firstName": "Daylily",
			"middleName": "Z",
			"lastName": "Fertile",
			"nameSuffix": "III",
			"ssn": "300402425",
			"dob": 1504483200000,
			"sourceSystemId": "68360",
			"link": "/hmis-clientapi/rest/v2020/clients/199b2f2f-44ee-4f85-973c-531819fb6b64",
			"projectGroupCode": "TT0013"
		},
		"bedUnit": {
			"id": "3db7b281-fc82-4850-919b-2c4fa7013ca7",
			"name": "Sp Bed 1",
			"occupancy": false,
			"occupantCapacity": 5,
			"overflow": true,
			"room": {
				"id": "80fe6023-ea22-48a0-b085-0c6886c6fae7",
				"name": "PnFkR",
				"occupantCapacity": 5,
				"area": {
					"id": "d4ace60f-dcf7-4671-a113-e7de3b000fb0",
					"name": "Ovosm",
					"description": "LMJSg",
					"occupantCapacity": 5,
					"shelter": {
						"id": "abf6c332-59d0-47f8-90cc-2fe61f2d4d95",
						"name": "Test shelter 11449",
						"address": "11449 North Fwy, Houston, TX 77060, USA",
						"url": "https://houston.com",
						"projectId": "3a8db874-418f-403b-b08f-a4cdba698e4e",
						"projectType": "BGkiQ",
						"description": "This is creation test shelter",
						"occupantCapacity": 5,
						"address1": "11449 North Freeway",
						"address2": "",
						"city": "Houston",
						"state": "Texas",
						"zipcode": "77060",
						"longitude": "-95.41336229999999",
						"latitude": "29.9328171"
					}
				},
				"shelter": {
					"id": "abf6c332-59d0-47f8-90cc-2fe61f2d4d95",
					"name": "Test shelter 11449",
					"address": "11449 North Fwy, Houston, TX 77060, USA",
					"url": "https://houston.com",
					"projectId": "3a8db874-418f-403b-b08f-a4cdba698e4e",
					"projectType": "BGkiQ",
					"description": "This is creation test shelter",
					"occupantCapacity": 5,
					"address1": "11449 North Freeway",
					"address2": "",
					"city": "Houston",
					"state": "Texas",
					"zipcode": "77060",
					"longitude": "-95.41336229999999",
					"latitude": "29.9328171"
				}
			}
		}
	}, {
		"id": "11eb4d8a-6959-4f94-8a22-1bdc9a3a127a",
		"startDate": 1610236800000,
		"endDate": 1611446399000,
		"bedUnit": {
			"id": "3db7b281-fc82-4850-919b-2c4fa7013ca7",
			"name": "Sp Bed 1",
			"occupancy": false,
			"occupantCapacity": 5,
			"overflow": true,
			"room": {
				"id": "80fe6023-ea22-48a0-b085-0c6886c6fae7",
				"name": "PnFkR",
				"occupantCapacity": 5,
				"area": {
					"id": "d4ace60f-dcf7-4671-a113-e7de3b000fb0",
					"name": "Ovosm",
					"description": "LMJSg",
					"occupantCapacity": 5,
					"shelter": {
						"id": "abf6c332-59d0-47f8-90cc-2fe61f2d4d95",
						"name": "Test shelter 11449",
						"address": "11449 North Fwy, Houston, TX 77060, USA",
						"url": "https://houston.com",
						"projectId": "3a8db874-418f-403b-b08f-a4cdba698e4e",
						"projectType": "BGkiQ",
						"description": "This is creation test shelter",
						"occupantCapacity": 5,
						"address1": "11449 North Freeway",
						"address2": "",
						"city": "Houston",
						"state": "Texas",
						"zipcode": "77060",
						"longitude": "-95.41336229999999",
						"latitude": "29.9328171"
					}
				},
				"shelter": {
					"id": "abf6c332-59d0-47f8-90cc-2fe61f2d4d95",
					"name": "Test shelter 11449",
					"address": "11449 North Fwy, Houston, TX 77060, USA",
					"url": "https://houston.com",
					"projectId": "3a8db874-418f-403b-b08f-a4cdba698e4e",
					"projectType": "BGkiQ",
					"description": "This is creation test shelter",
					"occupantCapacity": 5,
					"address1": "11449 North Freeway",
					"address2": "",
					"city": "Houston",
					"state": "Texas",
					"zipcode": "77060",
					"longitude": "-95.41336229999999",
					"latitude": "29.9328171"
				}
			}
		}
	}]
}

**Comment by suryayadavalli** [comment]
Resolved.
Commit id: https://github.com/servinglynk/hslynk-open-source/commit/4a52e4c90e30f9fcd1b5f2f2f77180b2abee516a

**Comment by logicsandeep** [comment]
PUT bed works fine now.
