### ISSUE TITLE
Do not reserve all the beds if a room is reserved.

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#37]
When a room is reserved we currently reserve all the beds and that is not correct. Any reservations to the room should go towards the room only.

**Comment by suryayadavalli** [comment]
Resolved. 
Commit id:  https://github.com/servinglynk/hslynk-open-source/commit/9f1209c509ce6b9cd800866efb923a0ad2d6da1e

**Comment by logicsandeep** [comment]
This issue can be closed.
https://github.com/servinglynk/hslynk-open-source/compare/08c950131a77...386eff197b1a
