### ISSUE TITLE
The bedlist apis also does not contain the total capacity, reserved beds, vacant beds counts at a summary level and area, room and shelter level

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#4]
The bedlist apis also does not contain the total capacity, reserved beds, vacant beds counts at a summary level and area, room and shelter level

**Comment by suryayadavalli** [comment]
**Work in progress.**  - ETA 12/14

Each GET API (GET /{shelterId}, GET /{areaId}, GET /{roomId} will inlcude the following summary information.

totalAreas (applicable only for GET by /{shelterId})
totalRooms  (applicable only for GET by /{shelterId} and GET by /{areaId})
totalBeds
reservedBeds
vacantBeds
occupiedBeds

**Comment by logicsandeep** [comment]
@suryayadavalli  We need that for the /shelters API too. We have a shelter list screen where we would like to show all of these values so a case worker does not have to go into the shelter to look. Having them at /{shelterid} and /{areaid} level is important too. But having it at /shelters level would help a lot.

**Comment by suryayadavalli** [comment]
@logicsandeep : okay, makes sense. Will include this  information at GET ALL shelters API

**Comment by logicsandeep** [comment]
Thanks @suryayadavalli

**Comment by suryayadavalli** [comment]
Worked on other issues. This is still in progress. Will complete the development by tomorrow 12/16

**Comment by suryayadavalli** [comment]
Worked on #20 as prioritized. Resuming the work on this issue today.

**Comment by suryayadavalli** [comment]
Commit id: https://github.com/servinglynk/hslynk-open-source/commit/40fbb3fd71b45d8ddfdd4289302bdfc6e75c7532

Updated documentation :  https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/

**Comment by logicsandeep** [comment]
This ticket can be closed.
