### ISSUE TITLE
Include latitude, longitude,city, state, zipcode and address 1 and address 2 in /POST and GET shelters API.

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#5]
Include latitude, longitude,city, state, zipcode and address 1 and address 2 in /POST and GET shelters API.

**Comment by suryayadavalli** [comment]
**Work in progress** 
ETA 12/11

**Comment by logicsandeep** [comment]
@suryayadavalli Are you going to deploy this today ?

**Comment by suryayadavalli** [comment]
commit id : https://github.com/servinglynk/hslynk-open-source/commit/499d565db149a3eef9d012cda93c92e4569976a6

**Comment by suryayadavalli** [comment]
Documentation link: https://docs.hslynk.com/?urls.primaryName=Bed%20Management%20API#/shelters/POST_shelter

**Comment by logicsandeep** [comment]
This can be fixed.
