### ISSUE TITLE
Include Shelter/Area/Room/BedUnit and Housing unit details in the golden view of a client.

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#6]
Include Shelter/Area/Room/BedUnit and Housing unit details in the golden view of a client.

**Comment by suryayadavalli** [comment]
12/11: **Not started**. Pub / Sub implementation is required. 

When the Housing unit / Bed unit is assigned to a client, an event will be triggered and Golden view metadata will be updated for the client. 

ETA: 12/17

**Comment by suryayadavalli** [comment]
commit id : https://github.com/servinglynk/hslynk-open-source/commit/c78b161ba74d0abe15702a62059111fe12430edb
Documentation link: https://docs.hslynk.com/?urls.primaryName=Global%20API#/default/GET_search-searchentity

**Comment by logicsandeep** [comment]
This can be closed
