### ISSUE TITLE
Populate the API documentation with the pagination parameters in the bedlist apis

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#9]
Populate the API documentation with the pagination parameters in the bedlist apis

**Comment by suryayadavalli** [comment]
** Work in progress **
ETA 12/11

**Comment by logicsandeep** [comment]
@suryayadavalli  I noticed that the shelter API does not have any pagination are you going to add them as well?
![Uploading Screen Shot 2020-12-11 at 4.51.36 AM.png…]()

**Comment by suryayadavalli** [comment]
Resolved. Commit id: https://github.com/hmis-api/bed-and-housing-management/commit/9244ba09f1223513cdfc0cfe26354a162dbbe98c

**Comment by logicsandeep** [comment]
Thanks, This can be closed.
